### PR TITLE
Cleaned up code and search url

### PR DESCRIPTION
**Pull request by porter707**
Cleaned up code:

- Added semi colons to all lines as only some had them
- Made indentation consistent 
- fixed search url as it had two "q" parameters e.g http://www.google.com/search?q=&oe=utf8&q=hello+world

### CODE REVIEW

**Comment by tartanguru** [comment]
Hi - I hadn't spotted that you had made changes.

I'll try and merge these in manually

**Comment by porter707** [comment]
Hi no problem I should be able to resolve the conflicts I'll give it a go now, think it's just adding the new code from your latest commit

**Comment by porter707** [comment]
I believe I've resolved them merge conflicts, best to double check it

**Comment by tartanguru** [comment]
Thanks! I appreciate you taking the time to clean it up. I'm pretty new to github, so I hadn't spotted your changes

**Pull request merged**
